window:
  
  # Title includes both 'alacritty' and 'terminal'
  title: Alacritty Terminal
  opacity: 0.83


  dimensions:
    columns: 168  
    lines: 42

  padding:
    x: 5
    y: 5
position:
    x: 30
    y: 10

  # More terminal 4 me
  decorations: none

colors:
  primary:
    background: '0x1f1f1f'
    foreground: '0xe5e1d8'

  # Normal colors
  normal:
    black:   '0x212c2a'
    red:     '0xff9580'
    green:   '0x8aff80'
    yellow:  '0xffff80'
    blue:    '0x9580ff'
    magenta: '0xff80bf'
    cyan:    '0x80ffea'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x212c2a'
    red:     '0xffaa99'
    green:   '0xa2ff99'
    yellow:  '0xffff99'
    blue:    '0xaa99ff'
    magenta: '0xff99cc'
    cyan:    '0x99ffee'
    white:   '0xffffff'


font:
  normal:
    family: roboto mono
  size: 6

shell:
  program: /usr/bin/tmux


key_bindings:
  - { key: T, mods: Shift|Control, chars: "\x06\x63"}  
  - { key: W, mods: Shift|Control, chars: "\x06\x78"}  
  - { key: H, mods: Shift|Control, chars: "\x06\x68"}  
  - { key: J, mods: Shift|Control, chars: "\x06\x6a"}  
  - { key: K, mods: Shift|Control, chars: "\x06\x6b"}  
  - { key: L, mods: Shift|Control, chars: "\x06\x6c"}  
  - { key: Tab, mods: Control, chars: "\x06\x6e"}  
  - { key: Tab, mods: Shift|Control, chars: "\x06\x70"}  
  - { key: Left, mods: Shift|Control, chars: "\x06\x48"}  
  - { key: Right, mods: Shift|Control, chars: "\x06\x4c"}  
  - { key: Down, mods: Shift|Control, chars: "\x06\x4a"}  
  - { key: Up, mods: Shift|Control, chars: "\x06\x4b"}  
